language: node_js
node_js: stable
branches:
  only:
    - hexo
cache:
  apt: true
  npm: true
  directories:
    - node_modules
before_install:
  - npm install -g hexo-cli
install:
  - npm i
script:
  - cp ./_theme_config.yml ./themes/next/_config.yml
  - hexo clean
  - hexo generate
after_success:
  - cp ./public/assets/images/practice-embed-html-in-jpeg4.jpg ./public/assets/images/practice-embed-html-in-jpeg4.html
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  local_dir: ./public
  github_token: $GITHUB_REPO_TOKEN  # Set in the settings page of your repository, as a secure variable
  on:
    branch: hexo
