language: node_js
node_js: stable
branches:
  only:
    - hexo
cache:
  apt: true
  npm: true
  directories:
    - node_modules
before_install:
  - git config --global user.name "breeze2"
  - git config --global user.email "805511939@qq.com"
  - npm install -g hexo-cli
install:
  - npm i
script:
  - cp ./_theme_config.yml ./themes/next/_config.yml
  - hexo clean
  - hexo generate
after_success:
  - cp ./public/assets/images/practice-embed-html-in-jpeg4.jpg ./public/assets/images/practice-embed-html-in-jpeg4.html
  - cd ./public
  - git init
  - git checkout --orphan gh-pages
  - git add -A
  - git commit -m "Travis CI Auto Builder"
  - git push --quiet --force https://$GITHUB_REPO_TOKEN@github.com/breeze2/blog gh-pages
